main/urls.py
from django.urls import path

from main.views import get_current_weather, get_weekly_weather, get_hourly_weather

app_name = 'main'

urlpatterns = [
    path('current_weather/', get_current_weather, name='current-weather'),
    path('weekly_weather/', get_weekly_weather, name='weekly-weather'),
    path('hourly_weather/', get_hourly_weather, name='hourly-weather'),
]

weather_client/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weather/', include('main.urls')),
]

main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from dotenv import load_dotenv

from main.utils import (
    response_api_current_weather,
    response_api_weekly_weather,
    response_api_hourly_weather,
)

load_dotenv()


def get_current_weather(request):
    if request.method == 'POST':
        city = request.POST.get('city')
        response = response_api_current_weather(city)
        if response.status_code == 200:
            weather_info = response.json()
            return render(
                request,
                'weather_app/current_weather.html',
                {'forecast': weather_info},
            )
        else:
            return HttpResponse('Failed to fetch weather data')

    return render(request, 'weather_app/current_weather_form.html')


def get_weekly_weather(request):
    if request.method == 'POST':
        city = request.POST.get('city')
        response = response_api_weekly_weather(city)
        if response.status_code == 200:
            weather_info = response.json()
            return render(
                request,
                'weather_app/weekly_weather.html',
                {'forecast': weather_info},
            )
        else:
            return HttpResponse('Failed to fetch weather data')

    return render(request, 'weather_app/weekly_weather_form.html')


def get_hourly_weather(request):
    if request.method == 'POST':
        city = request.POST.get('city')
        date = request.POST.get('date')

        response = response_api_hourly_weather(city)
        if response.status_code == 200:
            weather_info = response.json()

            selected_day = None
            for day in weather_info['forecast']['forecastday']:
                if day['date'] == date:
                    selected_day = day
                    break

            return render(
                request,
                'weather_app/hourly_weather.html',
                {
                    'forecast': selected_day,
                    'city': city,
                    'date': date,
                },
            )
        else:
            return HttpResponse('Failed to fetch hourly weather data')

    return render(request, 'weather_app/hourly_weather_form.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}Weather Report{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body class="body">

  {% block header %}
    {% include "includes/header.html" %}
  {% endblock %}

  <div class="container-fluid mt-1">
    <div class="row">

      <div class="col-sm-1"></div>

      <div class="col-sm-10">

        {% block content %}
        {% endblock %}

      </div>

      <div class="col-sm-1"></div>

    </div>
  </div>
</body>
</html>

templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <p class="navbar-brand">Weather Forecast</p>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item ">
          <a class="nav-link nav-link-a" href="{% url "main:current-weather" %}">Current weather</a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-a" href="{% url "main:hourly-weather" %}">Hourly weather</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link nav-link-a" href="{% url "main:weekly-weather" %}">Weekly weather</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/weather_app/current_weather.html
{% extends "base.html" %}

{% block title %}Current Weather{% endblock %}

{% block content %}
  <div class="weather-container">
    <h1>Current Weather for {{ forecast.location.name }}</h1>
    <img class="current-weather-icon" src="{{ forecast.current.condition.icon }}" alt="Weather Icon">
    <p class="current-weather-description">{{ forecast.current.condition.text }}</p>
    <p class="current-temperature">{{ forecast.current.temp_c }}°C</p>
    <p class="current-wind">Wind: {{ forecast.current.wind_kph }} km/h
      <span class="current-wind-direction" style="display: inline-block;
                transform: rotate({{ forecast.current.wind_degree }}deg);
                transition: transform 0.5s ease;">&#8593;
      </span>
    </p>
  </div>
{% endblock %}

templates/weather_app/current_weather_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Current Weather Form{% endblock %}

{% block content %}
  <h1>Current Weather</h1>
  <form method="post" action="{% url 'main:current-weather' %}" class="form">
    {% csrf_token %}
    {{ form|crispy }}
    <label for="city">Enter city:</label>
    <input type="text" name="city" required class="form-control">
    <button type="submit" class="btn btn-primary mt-4">Get Weather Report</button>
  </form>
{% endblock %}

templates/weather_app/hourly_weather.html
{% extends "base.html" %}

{% block title %}Hourly Weather{% endblock %}

{% block content %}
  <div class="weather-container">
    <h1>Hourly Weather Forecast for {{ city }} ({{ date }})</h1>
    <table class="weather-table">
      <thead>
        <tr>
          <th>Time</th>
          <th>Temperature (°C)</th>
          <th>Wind Speed (km/h)</th>
        </tr>
      </thead>
      <tbody>
        {% for hour in forecast.hour %}
          <tr>
            <td>{{ hour.time.split.1 }}</td>
            <td>{{ hour.temp_c }}</td>
            <td>{{ hour.wind_kph }}<span class="wind-direction ml-3" style="display: inline-block;
              transform: rotate({{ hour.wind_degree }}deg);
              transition: transform 0.5s ease;">&#8593;</span></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/weather_app/hourly_weather_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Hourly Weather Form{% endblock %}

{% block content %}
  <h1>Hourly Weather</h1>
  <form method="post" action="{% url 'main:hourly-weather' %}" class="form">
    {% csrf_token %}
    {{ form|crispy }}
    <label for="city">Enter city:</label>
    <input type="text" name="city" required class="form-control">
    <label for="date">Select date (nearly 10 days only!):</label>
    <input type="date" name="date" required class="form-control">
    <button type="submit" class="btn btn-primary mt-4">Get Hourly Weather</button>
  </form>
{% endblock %}

templates/weather_app/weather_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Weather Form</title>
</head>
<body>
    <h1>Weather Form</h1>
    <form method="post" action="{% url 'main:current-weather' %}">
        {% csrf_token %}
        <label for="city">Enter city:</label>
        <input type="text" name="city" required>
        <button type="submit">Get Weather Report</button>
    </form>
</body>
</html>

templates/weather_app/weekly_weather.html
{% extends "base.html" %}

{% block title %}Weekly Weather{% endblock %}

{% block content %}
  <div class="weather-container">
    <h1>Weekly Weather Forecast for {{ forecast.location.name }}</h1>
    <table class="weather-table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Min Temperature (°C)</th>
          <th>Max Temperature (°C)</th>
          <th>Precipitation Probability (%)</th>
        </tr>
      </thead>
      <tbody>
        {% for day in forecast.forecast.forecastday %}
          <tr>
            <td>{{ day.date }}</td>
            <td>{{ day.day.mintemp_c }}</td>
            <td>{{ day.day.maxtemp_c }}</td>
            <td>{{ day.day.daily_chance_of_rain }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/weather_app/weekly_weather_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Weekly Weather Form{% endblock %}

{% block content %}
  <h1>Weekly Weather</h1>
  <form method="post" action="{% url 'main:weekly-weather' %}" class="form">
    {% csrf_token %}
    {{ form|crispy }}
    <label for="city">Enter city:</label>
    <input type="text" name="city" required class="form-control">
    <button type="submit" class="btn btn-primary mt-4">Get Weekly Weather</button>
  </form>
{% endblock %}